use formuladb;


-- campionato
insert into campionato (anno, classe) values (2020, "Formula 1");



-- nazioni
insert into nazione(sigla, nome) values("AD", "ANDORRA");
insert into nazione(sigla, nome) values("AE", "EMIRATI ARABI UNITI");
insert into nazione(sigla, nome) values("AG", "ANTIGUA/BARBUDA");
insert into nazione(sigla, nome) values("AI", "ANGUILLA");
insert into nazione(sigla, nome) values("AL", "ALBANIA");
insert into nazione(sigla, nome) values("AM", "ARMENIA");
insert into nazione(sigla, nome) values("AN", "ANTILLE OLANDESI");
insert into nazione(sigla, nome) values("AO", "ANGOLA");
insert into nazione(sigla, nome) values("AR", "ARGENTINA");
insert into nazione(sigla, nome) values("AS", "SAMOA (USA)");
insert into nazione(sigla, nome) values("AT", "AUSTRIA");
insert into nazione(sigla, nome) values("AU", "AUSTRALIA");
insert into nazione(sigla, nome) values("AW", "ARUBA");
insert into nazione(sigla, nome) values("AZ", "AZERBAIGIAN");
insert into nazione(sigla, nome) values("BA", "BOSNIA-ERZEGOVINA");
insert into nazione(sigla, nome) values("BB", "BARBADOS");
insert into nazione(sigla, nome) values("BD", "BANGLADESH");
insert into nazione(sigla, nome) values("BE", "BELGIO");
insert into nazione(sigla, nome) values("BF", "BURKINA FASO");
insert into nazione(sigla, nome) values("BG", "BULGARIA");
insert into nazione(sigla, nome) values("BH", "BAHRAIN");
insert into nazione(sigla, nome) values("BI", "BURUNDI");
insert into nazione(sigla, nome) values("BJ", "BENIN");
insert into nazione(sigla, nome) values("BM", "BERMUDE");
insert into nazione(sigla, nome) values("BN", "BRUNEI");
insert into nazione(sigla, nome) values("BO", "BOLIVIA");
insert into nazione(sigla, nome) values("BR", "BRASILE");
insert into nazione(sigla, nome) values("BS", "BAHAMA");
insert into nazione(sigla, nome) values("BT", "BHUTAN");
insert into nazione(sigla, nome) values("BW", "BOTSWANA");
insert into nazione(sigla, nome) values("BY", "BIELORUSSIA");
insert into nazione(sigla, nome) values("BZ", "BELIZE");
insert into nazione(sigla, nome) values("CA", "CANADA");
insert into nazione(sigla, nome) values("CC", "ISOLE COCOS");
insert into nazione(sigla, nome) values("CD", "REP. DEMOCRATICA CO");
insert into nazione(sigla, nome) values("CF", "CENTRAFRICA");
insert into nazione(sigla, nome) values("CG", "REPUBBLICA DEL CONG");
insert into nazione(sigla, nome) values("CH", "SVIZZERA");
insert into nazione(sigla, nome) values("CI", "COSTA DAVORIO");
insert into nazione(sigla, nome) values("CK", "ARCIPELAGO DI COOK");
insert into nazione(sigla, nome) values("CL", "CILE");
insert into nazione(sigla, nome) values("CM", "CAMERUN");
insert into nazione(sigla, nome) values("CN", "CINA");
insert into nazione(sigla, nome) values("CO", "COLOMBIA");
insert into nazione(sigla, nome) values("CR", "COSTA RICA");
insert into nazione(sigla, nome) values("CU", "CUBA");
insert into nazione(sigla, nome) values("CX", "ISOLE CHRISTMAS");
insert into nazione(sigla, nome) values("CY", "CIPRO");
insert into nazione(sigla, nome) values("CZ", "REPUBBLICA CECA");
insert into nazione(sigla, nome) values("DE", "GERMANIA");
insert into nazione(sigla, nome) values("DJ", "GIBUTI");
insert into nazione(sigla, nome) values("DK", "DANIMARCA");
insert into nazione(sigla, nome) values("DM", "DOMINICA");
insert into nazione(sigla, nome) values("DO", "REPUBBLICA DOMINICA");
insert into nazione(sigla, nome) values("DZ", "ALGERIA");
insert into nazione(sigla, nome) values("EC", "ECUADOR");
insert into nazione(sigla, nome) values("EE", "ESTONIA");
insert into nazione(sigla, nome) values("EG", "EGITTO");
insert into nazione(sigla, nome) values("ER", "ERITREA");
insert into nazione(sigla, nome) values("ES", "SPAGNA");
insert into nazione(sigla, nome) values("ET", "ETIOPIA");
insert into nazione(sigla, nome) values("FI", "FINLANDIA");
insert into nazione(sigla, nome) values("FJ", "ISOLE FIGI");
insert into nazione(sigla, nome) values("FK", "ISOLE FALKLAND");
insert into nazione(sigla, nome) values("FO", "ISOLE FAEROER");
insert into nazione(sigla, nome) values("FR", "FRANCIA");
insert into nazione(sigla, nome) values("GA", "GABON");
insert into nazione(sigla, nome) values("GB", "GRAN BRETAGNA");
insert into nazione(sigla, nome) values("GD", "GRENADA");
insert into nazione(sigla, nome) values("GE", "GEORGIA");
insert into nazione(sigla, nome) values("GF", "GUIANA FRANCESE");
insert into nazione(sigla, nome) values("GH", "GHANA");
insert into nazione(sigla, nome) values("GI", "GIBILTERRA");
insert into nazione(sigla, nome) values("GL", "GROENLANDIA");
insert into nazione(sigla, nome) values("GM", "GAMBIA");
insert into nazione(sigla, nome) values("GN", "REPUBBLICA DI GUINE");
insert into nazione(sigla, nome) values("GP", "GUADALUPA");
insert into nazione(sigla, nome) values("GQ", "GUINEA EQUATORIALE");
insert into nazione(sigla, nome) values("GR", "GRECIA");
insert into nazione(sigla, nome) values("GS", "GEORGIA DEL SUD E S");
insert into nazione(sigla, nome) values("GT", "GUATEMALA");
insert into nazione(sigla, nome) values("GU", "GUAM");
insert into nazione(sigla, nome) values("GW", "GUINEA-BISSAU");
insert into nazione(sigla, nome) values("GY", "GUIANA");
insert into nazione(sigla, nome) values("HK", "HONG KONG");
insert into nazione(sigla, nome) values("HN", "HONDURAS");
insert into nazione(sigla, nome) values("HR", "CROAZIA");
insert into nazione(sigla, nome) values("HT", "HAITI");
insert into nazione(sigla, nome) values("HU", "UNGHERIA");
insert into nazione(sigla, nome) values("ID", "INDONESIA");
insert into nazione(sigla, nome) values("IE", "IRLANDA");
insert into nazione(sigla, nome) values("IL", "ISRAELE");
insert into nazione(sigla, nome) values("IN", "INDIA");
insert into nazione(sigla, nome) values("IQ", "IRAQ");
insert into nazione(sigla, nome) values("IR", "IRAN");
insert into nazione(sigla, nome) values("IS", "ISLANDA");
insert into nazione(sigla, nome) values("IT", "ITALIA");
insert into nazione(sigla, nome) values("JM", "GIAMAICA");
insert into nazione(sigla, nome) values("JO", "GIORDANIA");
insert into nazione(sigla, nome) values("JP", "GIAPPONE");
insert into nazione(sigla, nome) values("KE", "KENYA");
insert into nazione(sigla, nome) values("KG", "KIRGHIZISTAN");
insert into nazione(sigla, nome) values("KH", "CAMBOGIA");
insert into nazione(sigla, nome) values("KI", "KIRIBATI");
insert into nazione(sigla, nome) values("KM", "COMORE");
insert into nazione(sigla, nome) values("KN", "SAN CRISTOFORO E NE");
insert into nazione(sigla, nome) values("KP", "COREA DEL NORD");
insert into nazione(sigla, nome) values("KR", "COREA DEL SUD");
insert into nazione(sigla, nome) values("KW", "KUWAIT");
insert into nazione(sigla, nome) values("KY", "CAYMAN");
insert into nazione(sigla, nome) values("KZ", "KAZAKISTAN");
insert into nazione(sigla, nome) values("LA", "LAOS");
insert into nazione(sigla, nome) values("LB", "LIBANO");
insert into nazione(sigla, nome) values("LC", "SANTA LUCIA");
insert into nazione(sigla, nome) values("LI", "LIECHTENSTEIN");
insert into nazione(sigla, nome) values("LK", "SRI LANKA");
insert into nazione(sigla, nome) values("LR", "LIBERIA");
insert into nazione(sigla, nome) values("LS", "LESOTHO");
insert into nazione(sigla, nome) values("LT", "LITUANIA");
insert into nazione(sigla, nome) values("LU", "LUSSEMBURGO");
insert into nazione(sigla, nome) values("LV", "LETTONIA");
insert into nazione(sigla, nome) values("LY", "LIBIA");
insert into nazione(sigla, nome) values("MA", "MAROCCO");
insert into nazione(sigla, nome) values("MC", "MONTECARLO");
insert into nazione(sigla, nome) values("MD", "MOLDAVIA");
insert into nazione(sigla, nome) values("MG", "MADAGASCAR");
insert into nazione(sigla, nome) values("MH", "ISOLE MARSHALL");
insert into nazione(sigla, nome) values("MK", "MACEDONIA");
insert into nazione(sigla, nome) values("ML", "MALI");
insert into nazione(sigla, nome) values("MM", "MYANMAR (UNIONE)");
insert into nazione(sigla, nome) values("MN", "MONGOLIA");
insert into nazione(sigla, nome) values("MO", "MACAO");
insert into nazione(sigla, nome) values("MP", "ISOLE MARIANNE");
insert into nazione(sigla, nome) values("MQ", "MARTINICA");
insert into nazione(sigla, nome) values("MR", "MAURITANIA");
insert into nazione(sigla, nome) values("MS", "MONTSERRAT");
insert into nazione(sigla, nome) values("MT", "MALTA");
insert into nazione(sigla, nome) values("MU", "MAURIZIO");
insert into nazione(sigla, nome) values("MV", "MALDIVE");
insert into nazione(sigla, nome) values("MW", "MALAWI");
insert into nazione(sigla, nome) values("MX", "MESSICO");
insert into nazione(sigla, nome) values("MY", "MALAISIA");
insert into nazione(sigla, nome) values("MZ", "MOZAMBICO");
insert into nazione(sigla, nome) values("NA", "NAMIBIA");
insert into nazione(sigla, nome) values("NC", "NUOVA CALEDONIA");
insert into nazione(sigla, nome) values("NE", "NIGER");
insert into nazione(sigla, nome) values("NF", "ISOLA DI NORFOLK");
insert into nazione(sigla, nome) values("NG", "NIGERIA");
insert into nazione(sigla, nome) values("NI", "NICARAGUA");
insert into nazione(sigla, nome) values("NL", "PAESI BASSI");
insert into nazione(sigla, nome) values("NO", "NORVEGIA");
insert into nazione(sigla, nome) values("NP", "NEPAL");
insert into nazione(sigla, nome) values("NR", "NAURU");
insert into nazione(sigla, nome) values("NZ", "NUOVA ZELANDA");
insert into nazione(sigla, nome) values("OM", "OMAN");
insert into nazione(sigla, nome) values("PA", "PANAMA");
insert into nazione(sigla, nome) values("PE", "PERU");
insert into nazione(sigla, nome) values("PF", "POLINESIA FRANCESE");
insert into nazione(sigla, nome) values("PG", "PAPUA-NUOVA GUINEA");
insert into nazione(sigla, nome) values("PH", "FILIPPINE");
insert into nazione(sigla, nome) values("PK", "PAKISTAN");
insert into nazione(sigla, nome) values("PL", "POLONIA");
insert into nazione(sigla, nome) values("PM", "SAINT-PIERRE ET MIQ");
insert into nazione(sigla, nome) values("PN", "PITCAIRN");
insert into nazione(sigla, nome) values("PR", "PORTORICO");
insert into nazione(sigla, nome) values("PT", "PORTOGALLO");
insert into nazione(sigla, nome) values("PW", "ISOLE PALAU");
insert into nazione(sigla, nome) values("PY", "PARAGUAY");
insert into nazione(sigla, nome) values("QA", "QATAR");
insert into nazione(sigla, nome) values("RE", "REUNION");
insert into nazione(sigla, nome) values("RO", "ROMANIA");
insert into nazione(sigla, nome) values("RU", "RUSSIA");
insert into nazione(sigla, nome) values("RW", "RUANDA");
insert into nazione(sigla, nome) values("SA", "ARABIA SAUDITA");
insert into nazione(sigla, nome) values("SB", "ISOLE SALOMONE");
insert into nazione(sigla, nome) values("SC", "SEYCHELLES");
insert into nazione(sigla, nome) values("SD", "SUDAN");
insert into nazione(sigla, nome) values("SE", "SVEZIA");
insert into nazione(sigla, nome) values("SG", "SINGAPORE");
insert into nazione(sigla, nome) values("SH", "ASCENSION");
insert into nazione(sigla, nome) values("SI", "SLOVENIA");
insert into nazione(sigla, nome) values("SK", "REPUBBLICA SLOVACCA");
insert into nazione(sigla, nome) values("SL", "SIERRA LEONE");
insert into nazione(sigla, nome) values("SM", "SAN MARINO");
insert into nazione(sigla, nome) values("SN", "SENEGAL");
insert into nazione(sigla, nome) values("SO", "SOMALIA");
insert into nazione(sigla, nome) values("SR", "SURINAME");
insert into nazione(sigla, nome) values("ST", "SAO TOME E PRINCIP");
insert into nazione(sigla, nome) values("SU", "UNIONE SOVIETICA");
insert into nazione(sigla, nome) values("SV", "SALVADOR");
insert into nazione(sigla, nome) values("SY", "SIRIA");
insert into nazione(sigla, nome) values("SZ", "SWAZILAND");
insert into nazione(sigla, nome) values("TC", "TURKS E CAICOS");
insert into nazione(sigla, nome) values("TD", "CIAD");
insert into nazione(sigla, nome) values("TF", "ANTARTIDE FRANCESE");
insert into nazione(sigla, nome) values("TG", "TOGO");
insert into nazione(sigla, nome) values("TH", "TAILANDIA");
insert into nazione(sigla, nome) values("TJ", "TAGISKISTAN");
insert into nazione(sigla, nome) values("TK", "ISOLE TOKELAU");
insert into nazione(sigla, nome) values("TM", "TURKMENISTAN");
insert into nazione(sigla, nome) values("TN", "TUNISIA");
insert into nazione(sigla, nome) values("TO", "TONGA");
insert into nazione(sigla, nome) values("TP", "TIMOR ORIENTALE");
insert into nazione(sigla, nome) values("TR", "TURCHIA");
insert into nazione(sigla, nome) values("TT", "TRINIDAD E TOBAGO");
insert into nazione(sigla, nome) values("TV", "TUVALU");
insert into nazione(sigla, nome) values("TW", "TAIWAN");
insert into nazione(sigla, nome) values("TZ", "TANZANIA");
insert into nazione(sigla, nome) values("UA", "UCRAINA");
insert into nazione(sigla, nome) values("UG", "UGANDA");
insert into nazione(sigla, nome) values("UM", "ISOLE MINORI (USA)");
insert into nazione(sigla, nome) values("US", "STATI UNITI D'AMERICA");
insert into nazione(sigla, nome) values("UY", "URUGUAY");
insert into nazione(sigla, nome) values("UZ", "UZBEKISTAN");
insert into nazione(sigla, nome) values("VA", "CITTA DEL VATICANO");
insert into nazione(sigla, nome) values("VC", "SAINT VINCENT E GRE");
insert into nazione(sigla, nome) values("VE", "VENEZUELA");
insert into nazione(sigla, nome) values("VG", "ISOLE VERGINI (BRITANNIA)");
insert into nazione(sigla, nome) values("VI", "ISOLE VERGINI (USA)");
insert into nazione(sigla, nome) values("VN", "VIETNAM");
insert into nazione(sigla, nome) values("VU", "VANUATU");
insert into nazione(sigla, nome) values("WF", "WALLIS E FUTUNA");
insert into nazione(sigla, nome) values("WS", "SAMOA OCCIDENTALI");
insert into nazione(sigla, nome) values("XZ", "KOSOVO");
insert into nazione(sigla, nome) values("YE", "YEMEN");
insert into nazione(sigla, nome) values("YT", "MAYOTTE");
insert into nazione(sigla, nome) values("YU", "SERBIA E MONTENEGRO");
insert into nazione(sigla, nome) values("ZA", "SUD AFRICA");
insert into nazione(sigla, nome) values("ZM", "ZAMBIA");
insert into nazione(sigla, nome) values("ZR", "ZAIRE");
insert into nazione(sigla, nome) values("ZW", "ZIMBABWE");



-- circuito
insert into circuito (lunghezza, nome, nazione, citta) value (4381, "Hungaroring", "HU", "Mogyorod");
insert into circuito (lunghezza, nome, nazione, citta) value (5807, "Suzuka F1", "JP", "Nagoya");
insert into circuito (lunghezza, nome, nazione, citta) value (5513, "circuito delle Americhe", "US", "Austin");
insert into circuito (lunghezza, nome, nazione, citta) value (3337, "circuito di Monaco", "MC", "Monaco");
insert into circuito (lunghezza, nome, nazione, citta) value (4361, "circuito Gilles Villeneuve", "CA", "Montreal");
insert into circuito (lunghezza, nome, nazione, citta) value (4318, "anello Red Bull", "AT", "Spielberg");
insert into circuito (lunghezza, nome, nazione, citta) value (4933, "Autodromo E. & D. Ferrari", "IT", "Imola");
insert into circuito (lunghezza, nome, nazione, citta) value (5793, "Autodromo Nazionale Monza", "IT", "Monza");
insert into circuito (lunghezza, nome, nazione, citta) value (5412, "circuito internazionale del Bahrain", "BH", "Sakhir");
insert into circuito (lunghezza, nome, nazione, citta) value (5245, "Mugello", "IT", "Mugello");
insert into circuito (lunghezza, nome, nazione, citta) value (4655, "circuito di Catalunya", "ES", "Barcellona");
insert into circuito (lunghezza, nome, nazione, citta) value (4653, "circuito di Portimão", "PT", "Portimão");
insert into circuito (lunghezza, nome, nazione, citta) value (5848, "circuito di Sochi F1 Street", "RU", "Soci");
insert into circuito (lunghezza, nome, nazione, citta) value (6003, "circuito di Baku Street", "AZ", "Baku");
insert into circuito (lunghezza, nome, nazione, citta) value (5148, "Nürburgring", "DE", "Nürburg");
insert into circuito (lunghezza, nome, nazione, citta) value (5891, "circuito di Silverstone F1", "GB", "Silverstone");
insert into circuito (lunghezza, nome, nazione, citta) value (7004, "Spa-Francorchamps", "BE", "Terme");
insert into circuito (lunghezza, nome, nazione, citta) value (5303, "Albert Park F1", "AU", "Melbourne");
insert into circuito (lunghezza, nome, nazione, citta) value (5451, "circuito internazionale di Shanghai", "CN", "Shanghai");
insert into circuito (lunghezza, nome, nazione, citta) value (4252, "circuito Zandvoort", "NL", "Zandvoort");
insert into circuito (lunghezza, nome, nazione, citta) value (5554, "circuito di Yas Marina", "TR", "Abu Dhabi");




-- piloti
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (16, "LEC", "MC", "1997-10-16", "Charles", "Leclerc");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (5, "VET", "DE", "1987-07-03", "Sebastian", "Vettel");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (77, "BOT", "FI", "1989-08-28", "Valtteri", "Bottas");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (44, "HAM", "GB", "1985-01-07", "Lewis", "Hamilton");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (33, "VER", "NL", "1997-09-30", "Max", "Verstappen");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (23, "ALB", "TH", "1996-03-23", "Alexander", "Albon");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (55, "SAI", "ES", "1994-09-01", "Carlos", "Sainz");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (4, "NOR", "GB", "1999-11-13", "Lando", "Norris");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (3, "RIC", "AU", "1989-07-01", "Daniel", "Ricciardo");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (31, "OCO", "FR", "1996-09-17", "Esteban", "Ocon");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (26, "KVY", "RU", "1994-04-26", "Daniil", "Kvjat");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (10, "GAS", "FR", "1996-02-07", "Pierre", "Gasly");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (11, "PER", "MX", "1990-01-26", "Sergio", "Perez");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (18, "STR", "CA", "1998-10-29", "Lance", "Stroll");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (7, "RAI", "FI", "1979-10-17", "Kimi", "Raikkonen");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (99, "GIO", "IT", "1993-12-14", "Antonio", "Giovinazzi");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (8, "GRO", "FR", "1986-04-17", "Romain", "Grosjean");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (20, "MAG", "DK", "1992-10-05", "Kevin", "Magnussen");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (63, "RUS", "GB", "1998-02-15", "George", "Russell");
insert into pilota (numero, sigla, nazionalita, nascita, nome, cognome) value (6, "LAT", "CA", "1995-06-29", "Nicholas", "Latifi");




-- scuderia
insert into scuderia (nome, nazionalita) values ("Mercedes", "DE");
insert into scuderia (nome, nazionalita) values ("Ferrari", "IT");
insert into scuderia (nome, nazionalita) values ("Red Bull", "AT");
insert into scuderia (nome, nazionalita) values ("Renault", "FR");
insert into scuderia (nome, nazionalita) values ("Haas", "US");
insert into scuderia (nome, nazionalita) values ("McLaren", "GB");
insert into scuderia (nome, nazionalita) values ("Racing Point", "GB");
insert into scuderia (nome, nazionalita) values ("Alfa Romeo", "CH");
insert into scuderia (nome, nazionalita) values ("AlphaTauri", "IT");
insert into scuderia (nome, nazionalita) values ("Williams", "GB");






-- contratti scuderia pilota
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("BOT", "Mercedes", "2018-06-25", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("HAM", "Mercedes", "2017-10-21", 3 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("VET", "Ferrari", "2016-07-16", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("LEC", "Ferrari", "2016-11-02", 2 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("RAI", "Alfa Romeo", "2017-10-16", 1 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("GIO", "Alfa Romeo", "2016-08-02", 3 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("NOR", "McLaren", "2018-10-16", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("SAI", "McLaren", "2017-07-17", 5 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("VER", "Red Bull", "2017-06-16", 4 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("ALB", "Red Bull", "2016-10-07", 2 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("STR", "Racing Point", "2018-08-08", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("PER", "Racing Point", "2016-10-16", 5 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("RIC", "Renault", "2017-07-14", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("OCO", "Renault", "2016-10-16", 5 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("RUS", "Williams", "2018-08-05", 2 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("LAT", "Williams", "2016-06-11", null );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("GAS", "AlphaTauri", "2017-10-16", 2 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("KVY", "AlphaTauri", "2018-08-21", 1 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("GRO", "Haas", "2016-11-10", 1 );
insert into contratto_pilota (ID_pilota, ID_scuderia, data_inizio, durata_anni) values ("MAG", "Haas", "2017-10-04", null );



-- motori
insert into motore (nome, produttore, cavalli, alimentazione) values ("065 1.6 V6 turbo", "Ferrari", 930, "ibrido");
insert into motore (nome, produttore, cavalli, alimentazione) values ("M11 EQ Performance V6 turbo", "Mercedes", 1022, "ibrido");
insert into motore (nome, produttore, cavalli, alimentazione) values ("RA620H, V6 1.6 a 90° Turbo", "Red Bull", 740, "ibrido");
insert into motore (nome, produttore, cavalli, alimentazione) values ("E-TECH 20, V6 1.6 turbo", "Renault", 780, "ibrido");



insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Mercedes", 1, "F1ME2020", "E-TECH 20, V6 1.6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Ferrari", 1, "F1ME2020", "E-TECH 20, V6 1.6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Red Bull", 1, "F1RE2020", "065 1.6 V6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Renault", 1, "F1MFR020", "E-TECH 20, V6 1.6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Haas", 1, "F1HA2020", "RA620H, V6 1.6 a 90° Turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("McLaren", 1, "F1MC2020", "M11 EQ Performance V6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Racing Point", 1, "F1RP2020", "RA620H, V6 1.6 a 90° Turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Alfa Romeo", 1, "F1MAR020", "M11 EQ Performance V6 turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("AlphaTauri", 1, "F1AT2020", "RA620H, V6 1.6 a 90° Turbo");
insert into macchina (ID_scuderia, ID_campionato, nome, motore) values ("Williams", 1, "F1WI2020", "M11 EQ Performance V6 turbo");



-- info_gara
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-07-05 15-10-00", 60, "sole", "anello Red Bull", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-07-12 15-10-00", 60, "pioggia", "anello Red Bull", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-07-19 15-10-00", 63, "sole", "Hungaroring", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-08-02 15-10-00", 55, "sole", "circuito di Silverstone F1", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-08-09 15-10-00", 55, "nuvoloso", "circuito di Silverstone F1", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-08-16 15-10-00", 60, "sole", "circuito di Catalunya", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-08-30 15-10-00", 62, "nuvoloso", "Spa-Francorchamps", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-09-06 15-10-00", 63, "sole", "Autodromo Nazionale Monza", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-09-13 15-10-00", 71, "pioggia", "Mugello", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-09-27 13-10-00", 58, "sole", "circuito di Sochi F1 Street", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-10-11 14-10-00", 59, "pioggia", "Nürburgring", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-11-01 14-10-00", 61, "sole", "circuito di Portimão", 1);  -- forse data sbagliata ref https-//wheels.iconmagazine.it/sport/formula1/calendario-f1-2020-date-orari-gp#1gpaustriaredbullring5luglio2020
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-11-15 13-10-00", 65, "nuvoloso", "Autodromo E. & D. Ferrari", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-11-29 11-10-00", 67, "sole", "circuito internazionale del Bahrain", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-12-06 16-10-00", 60, "sole", "circuito internazionale del Bahrain", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-12-13 18-10-00", 56, "nuvoloso", "circuito internazionale del Bahrain", 1);
insert into info_gara (data_gara, n_giri, meteo, circuito, campionato) values ("2020-11-29 14-10-00", 65, "sole", "circuito di Yas Marina", 1);



insert into punti_posizione (posizione, punteggio) values (1, 25);
insert into punti_posizione (posizione, punteggio) values (2, 18);
insert into punti_posizione (posizione, punteggio) values (3, 15);
insert into punti_posizione (posizione, punteggio) values (4, 12);
insert into punti_posizione (posizione, punteggio) values (5, 10);
insert into punti_posizione (posizione, punteggio) values (6, 8);
insert into punti_posizione (posizione, punteggio) values (7, 6);
insert into punti_posizione (posizione, punteggio) values (8, 4);
insert into punti_posizione (posizione, punteggio) values (9, 2);
insert into punti_posizione (posizione, punteggio) values (10, 1);
insert into punti_posizione (posizione, punteggio) values (11, 0);
insert into punti_posizione (posizione, punteggio) values (12, 0);
insert into punti_posizione (posizione, punteggio) values (13, 0);
insert into punti_posizione (posizione, punteggio) values (14, 0);
insert into punti_posizione (posizione, punteggio) values (15, 0);
insert into punti_posizione (posizione, punteggio) values (16, 0);
insert into punti_posizione (posizione, punteggio) values (17, 0);
insert into punti_posizione (posizione, punteggio) values (18, 0);
insert into punti_posizione (posizione, punteggio) values (19, 0);
insert into punti_posizione (posizione, punteggio) values (20, 0);


insert into riepilogo(gara, pilota, scuderia) values(1, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(1, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(1, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(1, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(1, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(1, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(1, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(1, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(1, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(1, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(1, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(1, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(1, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(1, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(1, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(1, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(1, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(1, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(1, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(1, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(2, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(2, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(2, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(2, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(2, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(2, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(2, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(2, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(2, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(2, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(2, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(2, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(2, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(2, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(2, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(2, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(2, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(2, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(2, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(2, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(3, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(3, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(3, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(3, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(3, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(3, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(3, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(3, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(3, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(3, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(3, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(3, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(3, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(3, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(3, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(3, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(3, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(3, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(3, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(3, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(4, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(4, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(4, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(4, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(4, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(4, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(4, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(4, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(4, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(4, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(4, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(4, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(4, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(4, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(4, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(4, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(4, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(4, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(4, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(4, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(5, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(5, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(5, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(5, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(5, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(5, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(5, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(5, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(5, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(5, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(5, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(5, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(5, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(5, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(5, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(5, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(5, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(5, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(5, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(5, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(6, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(6, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(6, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(6, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(6, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(6, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(6, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(6, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(6, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(6, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(6, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(6, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(6, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(6, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(6, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(6, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(6, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(6, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(6, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(6, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(7, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(7, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(7, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(7, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(7, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(7, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(7, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(7, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(7, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(7, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(7, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(7, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(7, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(7, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(7, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(7, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(7, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(7, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(7, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(7, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(8, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(8, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(8, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(8, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(8, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(8, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(8, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(8, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(8, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(8, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(8, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(8, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(8, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(8, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(8, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(8, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(8, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(8, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(8, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(8, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(9, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(9, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(9, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(9, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(9, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(9, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(9, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(9, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(9, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(9, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(9, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(9, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(9, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(9, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(9, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(9, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(9, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(9, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(9, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(9, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(10, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(10, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(10, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(10, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(10, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(10, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(10, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(10, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(10, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(10, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(10, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(10, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(10, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(10, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(10, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(10, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(10, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(10, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(10, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(10, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(11, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(11, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(11, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(11, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(11, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(11, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(11, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(11, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(11, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(11, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(11, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(11, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(11, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(11, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(11, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(11, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(11, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(11, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(11, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(11, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(12, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(12, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(12, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(12, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(12, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(12, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(12, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(12, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(12, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(12, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(12, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(12, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(12, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(12, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(12, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(12, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(12, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(12, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(12, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(12, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(13, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(13, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(13, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(13, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(13, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(13, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(13, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(13, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(13, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(13, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(13, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(13, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(13, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(13, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(13, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(13, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(13, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(13, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(13, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(13, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(14, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(14, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(14, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(14, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(14, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(14, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(14, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(14, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(14, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(14, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(14, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(14, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(14, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(14, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(14, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(14, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(14, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(14, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(14, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(14, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(15, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(15, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(15, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(15, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(15, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(15, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(15, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(15, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(15, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(15, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(15, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(15, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(15, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(15, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(15, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(15, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(15, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(15, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(15, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(15, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(16, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(16, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(16, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(16, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(16, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(16, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(16, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(16, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(16, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(16, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(16, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(16, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(16, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(16, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(16, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(16, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(16, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(16, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(16, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(16, 'MAG', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(17, 'BOT', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(17, 'HAM', 'Mercedes');
insert into riepilogo(gara, pilota, scuderia) values(17, 'VET', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(17, 'LEC', 'Ferrari');
insert into riepilogo(gara, pilota, scuderia) values(17, 'RAI', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(17, 'GIO', 'Alfa Romeo');
insert into riepilogo(gara, pilota, scuderia) values(17, 'NOR', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(17, 'SAI', 'McLaren');
insert into riepilogo(gara, pilota, scuderia) values(17, 'VER', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(17, 'ALB', 'Red Bull');
insert into riepilogo(gara, pilota, scuderia) values(17, 'STR', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(17, 'PER', 'Racing Point');
insert into riepilogo(gara, pilota, scuderia) values(17, 'RIC', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(17, 'OCO', 'Renault');
insert into riepilogo(gara, pilota, scuderia) values(17, 'RUS', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(17, 'LAT', 'Williams');
insert into riepilogo(gara, pilota, scuderia) values(17, 'GAS', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(17, 'KVY', 'AlphaTauri');
insert into riepilogo(gara, pilota, scuderia) values(17, 'GRO', 'Haas');
insert into riepilogo(gara, pilota, scuderia) values(17, 'MAG', 'Haas');





-- ingegneri
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("fASEVSETFGHH", "spoiler", "IT", "1989-07-01", "Jacquelyn", "Watkins");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("RBYSDRBYDRSD", "motore", "IT", "1997-10-16", "Marta", "Osborne");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("BSDRYBDRBCKY", "minigonne", "IT", "1990-01-26", "Mercedes", "Hammond");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("EOJKGFSKLERG", "ruote", "BE", "1994-04-26", "Brent", "James");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("RGMSEPJKGWES", "spoiler", "US", "1994-04-26", "Alexandra", "Arnold");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("IOGJROIRHGES", "Telaio", "FR", "1993-12-14", "Pablo", "May");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("LSGKLEMGPKSM", "ruote", "GB", "1994-04-26", "Alice", "Quinn");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("GOKSRGOKASRG", "spoiler", "GB", "1997-10-16", "Andrew", "Yates");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("KRGMHALKRHNM", "motore", "FR", "1993-12-14", "Orville", "Bennett");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("EKGJPAOSJFOF", "Telaio", "TR", "1993-12-14", "Tommie", "Carr");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("GGPWIOEGMJWG", "spoiler", "GB", "1997-10-16", "Diane", "Ortiz");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("OCFWOPEGMIOW", "motore", "FR", "1992-10-05", "Don", "Saunders");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("FOAEKOPFKPOK", "Telaio", "TR", "1992-10-05", "Edna", "Bates");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("NEOFNEJONJEB", "motore", "GB", "1990-01-26", "Olivia", "Washington");
insert into ingegnere (CF, specialita, nazionalita, nascita, nome, cognome) values ("OPAOJPEJIJFI", "minigonne", "TR", "1992-10-05", "Ramiro", "Maxwell");



-- contratti piltoa
insert into contratto (CF, ID_scuderia) values ("fASEVSETFGHH", "Mercedes");
insert into contratto (CF, ID_scuderia) values ("RBYSDRBYDRSD", "Mercedes");
insert into contratto (CF, ID_scuderia) values ("BSDRYBDRBCKY", "Ferrari");
insert into contratto (CF, ID_scuderia) values ("EOJKGFSKLERG", "Ferrari");
insert into contratto (CF, ID_scuderia) values ("RGMSEPJKGWES", "Red Bull");
insert into contratto (CF, ID_scuderia) values ("IOGJROIRHGES", "Renault");
insert into contratto (CF, ID_scuderia) values ("LSGKLEMGPKSM", "Haas");
insert into contratto (CF, ID_scuderia) values ("GOKSRGOKASRG", "McLaren");
insert into contratto (CF, ID_scuderia) values ("KRGMHALKRHNM", "Racing Point");
insert into contratto (CF, ID_scuderia) values ("EKGJPAOSJFOF", "Alfa Romeo");
insert into contratto (CF, ID_scuderia) values ("GGPWIOEGMJWG", "AlphaTauri");
insert into contratto (CF, ID_scuderia) values ("OCFWOPEGMIOW", "Williams");
insert into contratto (CF, ID_scuderia) values ("FOAEKOPFKPOK", "Williams");
insert into contratto (CF, ID_scuderia) values ("NEOFNEJONJEB", "AlphaTauri");
insert into contratto (CF, ID_scuderia) values ("OPAOJPEJIJFI", "Alfa Romeo");






